model_name_or_path: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
output_dir: "runs/factcheck_relevance_cpu"
train_dir: "data/tevatron/train"
do_train: true
per_device_train_batch_size: 4
train_n_passages: 4
learning_rate: 0.00002
q_max_len: 64
p_max_len: 192
num_train_epochs: 10
save_steps: 2000
fp16: false
