# Global retrieval settings
model_name_or_path: "runs/factcheck_relevance_cpu"
output_dir: "runs/factcheck_relevance_global"
corpus_in_path: "data/global/corpus.jsonl"
corpus_out_path: "runs/factcheck_relevance_global/corpus.pkl"
query_in_path: "data/global/queries.jsonl"
query_out_path: "runs/factcheck_relevance_global/query.pkl"
run_path: "runs/factcheck_relevance_global/global.run"
qrels_path: "data/global/qrels.tsv"
topk: 50
p_max_len: 192
q_max_len: 64
per_device_eval_batch_size: 32
